name: CICD

on:
  push:
    branches:
      - master

jobs:

  login-and-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2


      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.repository_name }}


  access-and-run:
    needs: login-and-build-push
    runs-on: ubuntu-latest

    steps:
      - name: Access to target server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            seongheonjeong
            
            docker ps
            
            docker stop java-image

            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ github.repository_name }}
            
            docker run --rm --name java-image -d -p 3000:8080 ${{ secrets.DOCKER_USERNAME }}/${{ github.repository_name }}

            docker ps